/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAffiliatesRouteImport } from './routes/_authenticated/admin.affiliates'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin.audit-logs'
import { Route as AuthenticatedAdminMonitoringRouteImport } from './routes/_authenticated/admin.monitoring'
import { Route as AuthenticatedAdminParsedSignalsRouteImport } from './routes/_authenticated/admin.parsed-signals'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin.payouts'
import { Route as AuthenticatedAdminRiskTemplatesRouteImport } from './routes/_authenticated/admin.risk-templates'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSourcesRouteImport } from './routes/_authenticated/admin.sources'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminTelegramRouteImport } from './routes/_authenticated/admin.telegram'
import { Route as AuthenticatedAdminTradesRouteImport } from './routes/_authenticated/admin.trades'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppActiveTradesRouteImport } from './routes/_authenticated/app.active-trades'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app.analytics'
import { Route as AuthenticatedAppBacktestRouteImport } from './routes/_authenticated/app.backtest'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppExchangesRouteImport } from './routes/_authenticated/app.exchanges'
import { Route as AuthenticatedAppHeatmapRouteImport } from './routes/_authenticated/app.heatmap'
import { Route as AuthenticatedAppMarketplaceRouteImport } from './routes/_authenticated/app.marketplace'
import { Route as AuthenticatedAppPreferencesRouteImport } from './routes/_authenticated/app.preferences'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppReferralsRouteImport } from './routes/_authenticated/app.referrals'
import { Route as AuthenticatedAppRiskRouteImport } from './routes/_authenticated/app.risk'
import { Route as AuthenticatedAppRiskOptimizerRouteImport } from './routes/_authenticated/app.risk-optimizer'
import { Route as AuthenticatedAppSourcesRouteImport } from './routes/_authenticated/app.sources'
import { Route as AuthenticatedAppSupportRouteImport } from './routes/_authenticated/app.support'
import { Route as AuthenticatedAppTradeHistoryRouteImport } from './routes/_authenticated/app.trade-history'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicPaymentWebhookRouteImport } from './routes/api/public/payment-webhook'
import { Route as ApiPublicSignupHookRouteImport } from './routes/api/public/signup-hook'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicTelegramPhoneStartRouteImport } from './routes/api/public/telegram-phone-start'
import { Route as ApiPublicTelegramPhoneVerifyRouteImport } from './routes/api/public/telegram-phone-verify'
import { Route as ApiPublicHooksDispatchNotificationsRouteImport } from './routes/api/public/hooks/dispatch-notifications'
import { Route as ApiPublicHooksMonitorAnomaliesRouteImport } from './routes/api/public/hooks/monitor-anomalies'
import { Route as ApiPublicHooksMonitorPositionsRouteImport } from './routes/api/public/hooks/monitor-positions'
import { Route as ApiPublicHooksPriceTickRouteImport } from './routes/api/public/hooks/price-tick'
import { Route as ApiPublicHooksProcessOrdersRouteImport } from './routes/api/public/hooks/process-orders'
import { Route as ApiPublicHooksRunBacktestsRouteImport } from './routes/api/public/hooks/run-backtests'
import { Route as ApiPublicHooksSyncBalancesRouteImport } from './routes/api/public/hooks/sync-balances'
import { Route as ApiPublicHooksSyncPositionsRouteImport } from './routes/api/public/hooks/sync-positions'
import { Route as ApiPublicHooksWebhookSignalTokenRouteImport } from './routes/api/public/hooks/webhook-signal.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAffiliatesRoute =
  AuthenticatedAdminAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMonitoringRoute =
  AuthenticatedAdminMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParsedSignalsRoute =
  AuthenticatedAdminParsedSignalsRouteImport.update({
    id: '/parsed-signals',
    path: '/parsed-signals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRiskTemplatesRoute =
  AuthenticatedAdminRiskTemplatesRouteImport.update({
    id: '/risk-templates',
    path: '/risk-templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSourcesRoute =
  AuthenticatedAdminSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTelegramRoute =
  AuthenticatedAdminTelegramRouteImport.update({
    id: '/telegram',
    path: '/telegram',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTradesRoute =
  AuthenticatedAdminTradesRouteImport.update({
    id: '/trades',
    path: '/trades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppActiveTradesRoute =
  AuthenticatedAppActiveTradesRouteImport.update({
    id: '/active-trades',
    path: '/active-trades',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBacktestRoute =
  AuthenticatedAppBacktestRouteImport.update({
    id: '/backtest',
    path: '/backtest',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppExchangesRoute =
  AuthenticatedAppExchangesRouteImport.update({
    id: '/exchanges',
    path: '/exchanges',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHeatmapRoute = AuthenticatedAppHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMarketplaceRoute =
  AuthenticatedAppMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPreferencesRoute =
  AuthenticatedAppPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReferralsRoute =
  AuthenticatedAppReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRiskRoute = AuthenticatedAppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRiskOptimizerRoute =
  AuthenticatedAppRiskOptimizerRouteImport.update({
    id: '/risk-optimizer',
    path: '/risk-optimizer',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSourcesRoute = AuthenticatedAppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSupportRoute = AuthenticatedAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTradeHistoryRoute =
  AuthenticatedAppTradeHistoryRouteImport.update({
    id: '/trade-history',
    path: '/trade-history',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentWebhookRoute = ApiPublicPaymentWebhookRouteImport.update({
  id: '/api/public/payment-webhook',
  path: '/api/public/payment-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSignupHookRoute = ApiPublicSignupHookRouteImport.update({
  id: '/api/public/signup-hook',
  path: '/api/public/signup-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramPhoneStartRoute =
  ApiPublicTelegramPhoneStartRouteImport.update({
    id: '/api/public/telegram-phone-start',
    path: '/api/public/telegram-phone-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramPhoneVerifyRoute =
  ApiPublicTelegramPhoneVerifyRouteImport.update({
    id: '/api/public/telegram-phone-verify',
    path: '/api/public/telegram-phone-verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchNotificationsRoute =
  ApiPublicHooksDispatchNotificationsRouteImport.update({
    id: '/api/public/hooks/dispatch-notifications',
    path: '/api/public/hooks/dispatch-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonitorAnomaliesRoute =
  ApiPublicHooksMonitorAnomaliesRouteImport.update({
    id: '/api/public/hooks/monitor-anomalies',
    path: '/api/public/hooks/monitor-anomalies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonitorPositionsRoute =
  ApiPublicHooksMonitorPositionsRouteImport.update({
    id: '/api/public/hooks/monitor-positions',
    path: '/api/public/hooks/monitor-positions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPriceTickRoute = ApiPublicHooksPriceTickRouteImport.update({
  id: '/api/public/hooks/price-tick',
  path: '/api/public/hooks/price-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessOrdersRoute =
  ApiPublicHooksProcessOrdersRouteImport.update({
    id: '/api/public/hooks/process-orders',
    path: '/api/public/hooks/process-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunBacktestsRoute =
  ApiPublicHooksRunBacktestsRouteImport.update({
    id: '/api/public/hooks/run-backtests',
    path: '/api/public/hooks/run-backtests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncBalancesRoute =
  ApiPublicHooksSyncBalancesRouteImport.update({
    id: '/api/public/hooks/sync-balances',
    path: '/api/public/hooks/sync-balances',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncPositionsRoute =
  ApiPublicHooksSyncPositionsRouteImport.update({
    id: '/api/public/hooks/sync-positions',
    path: '/api/public/hooks/sync-positions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWebhookSignalTokenRoute =
  ApiPublicHooksWebhookSignalTokenRouteImport.update({
    id: '/api/public/hooks/webhook-signal/$token',
    path: '/api/public/hooks/webhook-signal/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/parsed-signals': typeof AuthenticatedAdminParsedSignalsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/risk-templates': typeof AuthenticatedAdminRiskTemplatesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/active-trades': typeof AuthenticatedAppActiveTradesRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/backtest': typeof AuthenticatedAppBacktestRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/exchanges': typeof AuthenticatedAppExchangesRoute
  '/app/heatmap': typeof AuthenticatedAppHeatmapRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/app/risk': typeof AuthenticatedAppRiskRoute
  '/app/risk-optimizer': typeof AuthenticatedAppRiskOptimizerRoute
  '/app/sources': typeof AuthenticatedAppSourcesRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/app/trade-history': typeof AuthenticatedAppTradeHistoryRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/signup-hook': typeof ApiPublicSignupHookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/telegram-phone-start': typeof ApiPublicTelegramPhoneStartRoute
  '/api/public/telegram-phone-verify': typeof ApiPublicTelegramPhoneVerifyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/api/public/hooks/monitor-anomalies': typeof ApiPublicHooksMonitorAnomaliesRoute
  '/api/public/hooks/monitor-positions': typeof ApiPublicHooksMonitorPositionsRoute
  '/api/public/hooks/price-tick': typeof ApiPublicHooksPriceTickRoute
  '/api/public/hooks/process-orders': typeof ApiPublicHooksProcessOrdersRoute
  '/api/public/hooks/run-backtests': typeof ApiPublicHooksRunBacktestsRoute
  '/api/public/hooks/sync-balances': typeof ApiPublicHooksSyncBalancesRoute
  '/api/public/hooks/sync-positions': typeof ApiPublicHooksSyncPositionsRoute
  '/api/public/hooks/webhook-signal/$token': typeof ApiPublicHooksWebhookSignalTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/parsed-signals': typeof AuthenticatedAdminParsedSignalsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/risk-templates': typeof AuthenticatedAdminRiskTemplatesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/active-trades': typeof AuthenticatedAppActiveTradesRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/backtest': typeof AuthenticatedAppBacktestRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/exchanges': typeof AuthenticatedAppExchangesRoute
  '/app/heatmap': typeof AuthenticatedAppHeatmapRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/app/risk': typeof AuthenticatedAppRiskRoute
  '/app/risk-optimizer': typeof AuthenticatedAppRiskOptimizerRoute
  '/app/sources': typeof AuthenticatedAppSourcesRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/app/trade-history': typeof AuthenticatedAppTradeHistoryRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/signup-hook': typeof ApiPublicSignupHookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/telegram-phone-start': typeof ApiPublicTelegramPhoneStartRoute
  '/api/public/telegram-phone-verify': typeof ApiPublicTelegramPhoneVerifyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/api/public/hooks/monitor-anomalies': typeof ApiPublicHooksMonitorAnomaliesRoute
  '/api/public/hooks/monitor-positions': typeof ApiPublicHooksMonitorPositionsRoute
  '/api/public/hooks/price-tick': typeof ApiPublicHooksPriceTickRoute
  '/api/public/hooks/process-orders': typeof ApiPublicHooksProcessOrdersRoute
  '/api/public/hooks/run-backtests': typeof ApiPublicHooksRunBacktestsRoute
  '/api/public/hooks/sync-balances': typeof ApiPublicHooksSyncBalancesRoute
  '/api/public/hooks/sync-positions': typeof ApiPublicHooksSyncPositionsRoute
  '/api/public/hooks/webhook-signal/$token': typeof ApiPublicHooksWebhookSignalTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/_authenticated/admin/parsed-signals': typeof AuthenticatedAdminParsedSignalsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/risk-templates': typeof AuthenticatedAdminRiskTemplatesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/_authenticated/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/app/active-trades': typeof AuthenticatedAppActiveTradesRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/backtest': typeof AuthenticatedAppBacktestRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/exchanges': typeof AuthenticatedAppExchangesRoute
  '/_authenticated/app/heatmap': typeof AuthenticatedAppHeatmapRoute
  '/_authenticated/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/_authenticated/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/_authenticated/app/risk': typeof AuthenticatedAppRiskRoute
  '/_authenticated/app/risk-optimizer': typeof AuthenticatedAppRiskOptimizerRoute
  '/_authenticated/app/sources': typeof AuthenticatedAppSourcesRoute
  '/_authenticated/app/support': typeof AuthenticatedAppSupportRoute
  '/_authenticated/app/trade-history': typeof AuthenticatedAppTradeHistoryRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/signup-hook': typeof ApiPublicSignupHookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/telegram-phone-start': typeof ApiPublicTelegramPhoneStartRoute
  '/api/public/telegram-phone-verify': typeof ApiPublicTelegramPhoneVerifyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/api/public/hooks/monitor-anomalies': typeof ApiPublicHooksMonitorAnomaliesRoute
  '/api/public/hooks/monitor-positions': typeof ApiPublicHooksMonitorPositionsRoute
  '/api/public/hooks/price-tick': typeof ApiPublicHooksPriceTickRoute
  '/api/public/hooks/process-orders': typeof ApiPublicHooksProcessOrdersRoute
  '/api/public/hooks/run-backtests': typeof ApiPublicHooksRunBacktestsRoute
  '/api/public/hooks/sync-balances': typeof ApiPublicHooksSyncBalancesRoute
  '/api/public/hooks/sync-positions': typeof ApiPublicHooksSyncPositionsRoute
  '/api/public/hooks/webhook-signal/$token': typeof ApiPublicHooksWebhookSignalTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate'
    | '/auth'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/app'
    | '/admin/affiliates'
    | '/admin/audit-logs'
    | '/admin/monitoring'
    | '/admin/parsed-signals'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/risk-templates'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/telegram'
    | '/admin/trades'
    | '/admin/users'
    | '/app/active-trades'
    | '/app/analytics'
    | '/app/backtest'
    | '/app/billing'
    | '/app/exchanges'
    | '/app/heatmap'
    | '/app/marketplace'
    | '/app/preferences'
    | '/app/profile'
    | '/app/referrals'
    | '/app/risk'
    | '/app/risk-optimizer'
    | '/app/sources'
    | '/app/support'
    | '/app/trade-history'
    | '/api/public/health'
    | '/api/public/payment-webhook'
    | '/api/public/signup-hook'
    | '/api/public/stripe-webhook'
    | '/api/public/telegram-phone-start'
    | '/api/public/telegram-phone-verify'
    | '/admin/'
    | '/app/'
    | '/api/public/hooks/dispatch-notifications'
    | '/api/public/hooks/monitor-anomalies'
    | '/api/public/hooks/monitor-positions'
    | '/api/public/hooks/price-tick'
    | '/api/public/hooks/process-orders'
    | '/api/public/hooks/run-backtests'
    | '/api/public/hooks/sync-balances'
    | '/api/public/hooks/sync-positions'
    | '/api/public/hooks/webhook-signal/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate'
    | '/auth'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/affiliates'
    | '/admin/audit-logs'
    | '/admin/monitoring'
    | '/admin/parsed-signals'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/risk-templates'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/telegram'
    | '/admin/trades'
    | '/admin/users'
    | '/app/active-trades'
    | '/app/analytics'
    | '/app/backtest'
    | '/app/billing'
    | '/app/exchanges'
    | '/app/heatmap'
    | '/app/marketplace'
    | '/app/preferences'
    | '/app/profile'
    | '/app/referrals'
    | '/app/risk'
    | '/app/risk-optimizer'
    | '/app/sources'
    | '/app/support'
    | '/app/trade-history'
    | '/api/public/health'
    | '/api/public/payment-webhook'
    | '/api/public/signup-hook'
    | '/api/public/stripe-webhook'
    | '/api/public/telegram-phone-start'
    | '/api/public/telegram-phone-verify'
    | '/admin'
    | '/app'
    | '/api/public/hooks/dispatch-notifications'
    | '/api/public/hooks/monitor-anomalies'
    | '/api/public/hooks/monitor-positions'
    | '/api/public/hooks/price-tick'
    | '/api/public/hooks/process-orders'
    | '/api/public/hooks/run-backtests'
    | '/api/public/hooks/sync-balances'
    | '/api/public/hooks/sync-positions'
    | '/api/public/hooks/webhook-signal/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/affiliate'
    | '/auth'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/admin/affiliates'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/monitoring'
    | '/_authenticated/admin/parsed-signals'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/risk-templates'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/sources'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/telegram'
    | '/_authenticated/admin/trades'
    | '/_authenticated/admin/users'
    | '/_authenticated/app/active-trades'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/backtest'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/exchanges'
    | '/_authenticated/app/heatmap'
    | '/_authenticated/app/marketplace'
    | '/_authenticated/app/preferences'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/referrals'
    | '/_authenticated/app/risk'
    | '/_authenticated/app/risk-optimizer'
    | '/_authenticated/app/sources'
    | '/_authenticated/app/support'
    | '/_authenticated/app/trade-history'
    | '/api/public/health'
    | '/api/public/payment-webhook'
    | '/api/public/signup-hook'
    | '/api/public/stripe-webhook'
    | '/api/public/telegram-phone-start'
    | '/api/public/telegram-phone-verify'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/api/public/hooks/dispatch-notifications'
    | '/api/public/hooks/monitor-anomalies'
    | '/api/public/hooks/monitor-positions'
    | '/api/public/hooks/price-tick'
    | '/api/public/hooks/process-orders'
    | '/api/public/hooks/run-backtests'
    | '/api/public/hooks/sync-balances'
    | '/api/public/hooks/sync-positions'
    | '/api/public/hooks/webhook-signal/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AffiliateRoute: typeof AffiliateRoute
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicPaymentWebhookRoute: typeof ApiPublicPaymentWebhookRoute
  ApiPublicSignupHookRoute: typeof ApiPublicSignupHookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicTelegramPhoneStartRoute: typeof ApiPublicTelegramPhoneStartRoute
  ApiPublicTelegramPhoneVerifyRoute: typeof ApiPublicTelegramPhoneVerifyRoute
  ApiPublicHooksDispatchNotificationsRoute: typeof ApiPublicHooksDispatchNotificationsRoute
  ApiPublicHooksMonitorAnomaliesRoute: typeof ApiPublicHooksMonitorAnomaliesRoute
  ApiPublicHooksMonitorPositionsRoute: typeof ApiPublicHooksMonitorPositionsRoute
  ApiPublicHooksPriceTickRoute: typeof ApiPublicHooksPriceTickRoute
  ApiPublicHooksProcessOrdersRoute: typeof ApiPublicHooksProcessOrdersRoute
  ApiPublicHooksRunBacktestsRoute: typeof ApiPublicHooksRunBacktestsRoute
  ApiPublicHooksSyncBalancesRoute: typeof ApiPublicHooksSyncBalancesRoute
  ApiPublicHooksSyncPositionsRoute: typeof ApiPublicHooksSyncPositionsRoute
  ApiPublicHooksWebhookSignalTokenRoute: typeof ApiPublicHooksWebhookSignalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/affiliates': {
      id: '/_authenticated/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AuthenticatedAdminAffiliatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/monitoring': {
      id: '/_authenticated/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AuthenticatedAdminMonitoringRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parsed-signals': {
      id: '/_authenticated/admin/parsed-signals'
      path: '/parsed-signals'
      fullPath: '/admin/parsed-signals'
      preLoaderRoute: typeof AuthenticatedAdminParsedSignalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/risk-templates': {
      id: '/_authenticated/admin/risk-templates'
      path: '/risk-templates'
      fullPath: '/admin/risk-templates'
      preLoaderRoute: typeof AuthenticatedAdminRiskTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sources': {
      id: '/_authenticated/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AuthenticatedAdminSourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/telegram': {
      id: '/_authenticated/admin/telegram'
      path: '/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AuthenticatedAdminTelegramRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trades': {
      id: '/_authenticated/admin/trades'
      path: '/trades'
      fullPath: '/admin/trades'
      preLoaderRoute: typeof AuthenticatedAdminTradesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/active-trades': {
      id: '/_authenticated/app/active-trades'
      path: '/active-trades'
      fullPath: '/app/active-trades'
      preLoaderRoute: typeof AuthenticatedAppActiveTradesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/backtest': {
      id: '/_authenticated/app/backtest'
      path: '/backtest'
      fullPath: '/app/backtest'
      preLoaderRoute: typeof AuthenticatedAppBacktestRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/exchanges': {
      id: '/_authenticated/app/exchanges'
      path: '/exchanges'
      fullPath: '/app/exchanges'
      preLoaderRoute: typeof AuthenticatedAppExchangesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/heatmap': {
      id: '/_authenticated/app/heatmap'
      path: '/heatmap'
      fullPath: '/app/heatmap'
      preLoaderRoute: typeof AuthenticatedAppHeatmapRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/marketplace': {
      id: '/_authenticated/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/preferences': {
      id: '/_authenticated/app/preferences'
      path: '/preferences'
      fullPath: '/app/preferences'
      preLoaderRoute: typeof AuthenticatedAppPreferencesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/referrals': {
      id: '/_authenticated/app/referrals'
      path: '/referrals'
      fullPath: '/app/referrals'
      preLoaderRoute: typeof AuthenticatedAppReferralsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/risk': {
      id: '/_authenticated/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AuthenticatedAppRiskRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/risk-optimizer': {
      id: '/_authenticated/app/risk-optimizer'
      path: '/risk-optimizer'
      fullPath: '/app/risk-optimizer'
      preLoaderRoute: typeof AuthenticatedAppRiskOptimizerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sources': {
      id: '/_authenticated/app/sources'
      path: '/sources'
      fullPath: '/app/sources'
      preLoaderRoute: typeof AuthenticatedAppSourcesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/support': {
      id: '/_authenticated/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AuthenticatedAppSupportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trade-history': {
      id: '/_authenticated/app/trade-history'
      path: '/trade-history'
      fullPath: '/app/trade-history'
      preLoaderRoute: typeof AuthenticatedAppTradeHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-webhook': {
      id: '/api/public/payment-webhook'
      path: '/api/public/payment-webhook'
      fullPath: '/api/public/payment-webhook'
      preLoaderRoute: typeof ApiPublicPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signup-hook': {
      id: '/api/public/signup-hook'
      path: '/api/public/signup-hook'
      fullPath: '/api/public/signup-hook'
      preLoaderRoute: typeof ApiPublicSignupHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-phone-start': {
      id: '/api/public/telegram-phone-start'
      path: '/api/public/telegram-phone-start'
      fullPath: '/api/public/telegram-phone-start'
      preLoaderRoute: typeof ApiPublicTelegramPhoneStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-phone-verify': {
      id: '/api/public/telegram-phone-verify'
      path: '/api/public/telegram-phone-verify'
      fullPath: '/api/public/telegram-phone-verify'
      preLoaderRoute: typeof ApiPublicTelegramPhoneVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-notifications': {
      id: '/api/public/hooks/dispatch-notifications'
      path: '/api/public/hooks/dispatch-notifications'
      fullPath: '/api/public/hooks/dispatch-notifications'
      preLoaderRoute: typeof ApiPublicHooksDispatchNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-anomalies': {
      id: '/api/public/hooks/monitor-anomalies'
      path: '/api/public/hooks/monitor-anomalies'
      fullPath: '/api/public/hooks/monitor-anomalies'
      preLoaderRoute: typeof ApiPublicHooksMonitorAnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-positions': {
      id: '/api/public/hooks/monitor-positions'
      path: '/api/public/hooks/monitor-positions'
      fullPath: '/api/public/hooks/monitor-positions'
      preLoaderRoute: typeof ApiPublicHooksMonitorPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/price-tick': {
      id: '/api/public/hooks/price-tick'
      path: '/api/public/hooks/price-tick'
      fullPath: '/api/public/hooks/price-tick'
      preLoaderRoute: typeof ApiPublicHooksPriceTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-orders': {
      id: '/api/public/hooks/process-orders'
      path: '/api/public/hooks/process-orders'
      fullPath: '/api/public/hooks/process-orders'
      preLoaderRoute: typeof ApiPublicHooksProcessOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-backtests': {
      id: '/api/public/hooks/run-backtests'
      path: '/api/public/hooks/run-backtests'
      fullPath: '/api/public/hooks/run-backtests'
      preLoaderRoute: typeof ApiPublicHooksRunBacktestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-balances': {
      id: '/api/public/hooks/sync-balances'
      path: '/api/public/hooks/sync-balances'
      fullPath: '/api/public/hooks/sync-balances'
      preLoaderRoute: typeof ApiPublicHooksSyncBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-positions': {
      id: '/api/public/hooks/sync-positions'
      path: '/api/public/hooks/sync-positions'
      fullPath: '/api/public/hooks/sync-positions'
      preLoaderRoute: typeof ApiPublicHooksSyncPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/webhook-signal/$token': {
      id: '/api/public/hooks/webhook-signal/$token'
      path: '/api/public/hooks/webhook-signal/$token'
      fullPath: '/api/public/hooks/webhook-signal/$token'
      preLoaderRoute: typeof ApiPublicHooksWebhookSignalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAffiliatesRoute: typeof AuthenticatedAdminAffiliatesRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminMonitoringRoute: typeof AuthenticatedAdminMonitoringRoute
  AuthenticatedAdminParsedSignalsRoute: typeof AuthenticatedAdminParsedSignalsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminRiskTemplatesRoute: typeof AuthenticatedAdminRiskTemplatesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSourcesRoute: typeof AuthenticatedAdminSourcesRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminTelegramRoute: typeof AuthenticatedAdminTelegramRoute
  AuthenticatedAdminTradesRoute: typeof AuthenticatedAdminTradesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAffiliatesRoute: AuthenticatedAdminAffiliatesRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminMonitoringRoute: AuthenticatedAdminMonitoringRoute,
  AuthenticatedAdminParsedSignalsRoute: AuthenticatedAdminParsedSignalsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
  AuthenticatedAdminRiskTemplatesRoute: AuthenticatedAdminRiskTemplatesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSourcesRoute: AuthenticatedAdminSourcesRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminTelegramRoute: AuthenticatedAdminTelegramRoute,
  AuthenticatedAdminTradesRoute: AuthenticatedAdminTradesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppActiveTradesRoute: typeof AuthenticatedAppActiveTradesRoute
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppBacktestRoute: typeof AuthenticatedAppBacktestRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppExchangesRoute: typeof AuthenticatedAppExchangesRoute
  AuthenticatedAppHeatmapRoute: typeof AuthenticatedAppHeatmapRoute
  AuthenticatedAppMarketplaceRoute: typeof AuthenticatedAppMarketplaceRoute
  AuthenticatedAppPreferencesRoute: typeof AuthenticatedAppPreferencesRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppReferralsRoute: typeof AuthenticatedAppReferralsRoute
  AuthenticatedAppRiskRoute: typeof AuthenticatedAppRiskRoute
  AuthenticatedAppRiskOptimizerRoute: typeof AuthenticatedAppRiskOptimizerRoute
  AuthenticatedAppSourcesRoute: typeof AuthenticatedAppSourcesRoute
  AuthenticatedAppSupportRoute: typeof AuthenticatedAppSupportRoute
  AuthenticatedAppTradeHistoryRoute: typeof AuthenticatedAppTradeHistoryRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppActiveTradesRoute: AuthenticatedAppActiveTradesRoute,
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppBacktestRoute: AuthenticatedAppBacktestRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppExchangesRoute: AuthenticatedAppExchangesRoute,
  AuthenticatedAppHeatmapRoute: AuthenticatedAppHeatmapRoute,
  AuthenticatedAppMarketplaceRoute: AuthenticatedAppMarketplaceRoute,
  AuthenticatedAppPreferencesRoute: AuthenticatedAppPreferencesRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppReferralsRoute: AuthenticatedAppReferralsRoute,
  AuthenticatedAppRiskRoute: AuthenticatedAppRiskRoute,
  AuthenticatedAppRiskOptimizerRoute: AuthenticatedAppRiskOptimizerRoute,
  AuthenticatedAppSourcesRoute: AuthenticatedAppSourcesRoute,
  AuthenticatedAppSupportRoute: AuthenticatedAppSupportRoute,
  AuthenticatedAppTradeHistoryRoute: AuthenticatedAppTradeHistoryRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AffiliateRoute: AffiliateRoute,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicPaymentWebhookRoute: ApiPublicPaymentWebhookRoute,
  ApiPublicSignupHookRoute: ApiPublicSignupHookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicTelegramPhoneStartRoute: ApiPublicTelegramPhoneStartRoute,
  ApiPublicTelegramPhoneVerifyRoute: ApiPublicTelegramPhoneVerifyRoute,
  ApiPublicHooksDispatchNotificationsRoute:
    ApiPublicHooksDispatchNotificationsRoute,
  ApiPublicHooksMonitorAnomaliesRoute: ApiPublicHooksMonitorAnomaliesRoute,
  ApiPublicHooksMonitorPositionsRoute: ApiPublicHooksMonitorPositionsRoute,
  ApiPublicHooksPriceTickRoute: ApiPublicHooksPriceTickRoute,
  ApiPublicHooksProcessOrdersRoute: ApiPublicHooksProcessOrdersRoute,
  ApiPublicHooksRunBacktestsRoute: ApiPublicHooksRunBacktestsRoute,
  ApiPublicHooksSyncBalancesRoute: ApiPublicHooksSyncBalancesRoute,
  ApiPublicHooksSyncPositionsRoute: ApiPublicHooksSyncPositionsRoute,
  ApiPublicHooksWebhookSignalTokenRoute: ApiPublicHooksWebhookSignalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
